---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

########################################################################################################################################################################################################
- Network System:
    # - Primary PiHole:
    #     icon: pi-hole.png
    #     href: http://pihole.emporer.net
    #     container: pihole
    #     server: emporer-docker
    #     description: Primary network-wide ad blocker (emporer.net)
    #     widgets:
    #         - type: pihole
    #           url: http://pihole.emporer.net
    #           version: 6
    #           highlight:
    #             queries:
    #                 string:
    #                     - level: danger
    #                       when: equals
    #                       value: "0"
    #             blocked:
    #                 string:
    #                     - level: danger
    #                       when: regex
    #                       value: "\\(0%\\)"
    #             gravity:
    #                 string:
    #                     - level: danger
    #                       when: equals
    #                       value: "0"
    - Secondary PiHole:
        icon: pi-hole.png
        href: http://pihole.volo.nas/admin
        container: ix-pihole-pihole-1
        server: volo-docker
        description: Secondary network-wide ad blocker (volo.nas)
        widgets:
            - type: pihole
              url: http://pihole.volo.nas
              version: 6
              highlight:
                queries:
                    string:
                        - level: danger
                          when: equals
                          value: "0"
                blocked:
                    string:
                        - level: danger
                          when: regex
                          value: "\\(0%\\)"
                gravity:
                    string:
                        - level: danger
                          when: equals
                          value: "0"
    - Speedtest:
        icon: speedtest-tracker.png
        href: http://speed.volo.nas
        server: emporer-docker
        container: ix-speedtest-tracker-speedtest-tracker-1
        description: Network speed tracker
        widget:
            type: speedtest
            url: http://speed.volo.nas
            bitratePrecision: 0
            fields: ["download", "upload", "ping"]
            highlight:
                download:
                    numeric:
                        - level: danger
                          when: lte
                          value: 250
                        - level: warn
                          when: lte
                          value: 450
                        - level: good
                          when: gte
                          value: 450
                upload:
                    numeric:
                        - level: danger
                          when: lte
                          value: 25
                        - level: warn
                          when: lte
                          value: 45
                        - level: good
                          when: gte
                          value: 45
                ping:
                    numeric:
                        - level: danger
                          when: gte
                          value: 50
                        - level: warn
                          when: gte
                          value: 20
                        - level: good
                          when: lt
                          value: 20
########################################################################################################################################################################################################
- Network:
    - nGinx:
        icon: nginx.png
        href: http://nginx.volo.nas
        container: ix-nginx-proxy-manager-npm-1
        server: emporer-docker
        description: Web server and reverse proxy
        widget:
            type: npm
            url: http://nginx.volo.nas
            username: calza27@gmail.com
            password: {{HOMEPAGE_FILE_NGINX_KEY}}
    - unifi:
        icon: unifi.png
        href: https://192.168.3.21
        description: Network management controller
        widget:
            type: unifi
            url: https://192.168.3.21
            key: {{HOMEPAGE_FILE_UNIFI_KEY}}
            highlight:
                wlan:
                    string:
                        - level: danger
                          when: equals
                          negate: true
                          value: "UP"
                        - level: good
                          when: equals
                          value: "UP"
                wlan_devices:
                    numeric:
                        - level: danger
                          when: equals
                          value: 0
                        - level: good
                          when: gt
                          value: 0
                wlan_users:
                    numeric:
                        - level: warn
                          when: equals
                          value: 0
                        - level: good
                          when: gt
                          value: 0
########################################################################################################################################################################################################
- Media System:
    - truenas:
        icon: truenas.png
        href: http://volo.nas
        description: The OS
        widget:
            type: truenas
            url: http://volo.nas
            version: 2
            key: {{HOMEPAGE_FILE_TRUENAS_KEY}}
            enablePools: true 
            nasType: core
    - nGinx:
        icon: nginx.png
        href: http://nginx.volo.nas
        container: ix-nginx-proxy-manager-npm-1
        server: volo-docker
        description: Web server and reverse proxy
        widget:
            type: npm
            url: http://nginx.volo.nas
            username: calza27@gmail.com
            password: {{HOMEPAGE_FILE_NGINX_KEY}}
    - qBitTorrent:
        icon: qbittorrent.png
        href: http://qbit.volo.nas
        container: qbittorrent
        server: volo-docker
        description: Torrent client
        widget:
            type: qbittorrent
            url: http://qbit.volo.nas
            username: admin
            password: {{HOMEPAGE_FILE_QBIT_KEY}}
            enableLeechProgress: true
            enableLeechSize: true
    - Uptime:
        icon: uptime-kuma.png
        href: http://kuma.volo.nas
        container: ix-uptime-kuma-uptime-kuma-1
        server: volo-docker
        description: Monitor the status of your services
        widgets:
            - type: uptimekuma
              url: http://kuma.volo.nas
              slug: media-stack
              fields: ["up", "down", "uptime"]
              highlight:
                up:
                    numeric:
                        - level: danger
                          when: eq
                          value: 0
                down:
                    numeric:
                        - level: warn
                          when: gte
                          value: 1
                        - level: good
                          when: eq
                          value: 0
                uptime:
                    numeric:
                        - level: danger
                          when: lt
                          value: 80
                        - level: warn
                          when: lt
                          value: 98
                        - level: good
                          when: gte
                          value: 98
            - type: uptimekuma
              url: http://kuma.volo.nas
              slug: support-svcs
              fields: ["up", "down", "uptime"]
              highlight:
                up:
                    numeric:
                        - level: danger
                          when: eq
                          value: 0
                down:
                    numeric:
                        - level: warn
                          when: gte
                          value: 1
                        - level: good
                          when: eq
                          value: 0
                uptime:
                    numeric:
                        - level: danger
                          when: lt
                          value: 80
                        - level: warn
                          when: lt
                          value: 98
                        - level: good
                          when: gte
                          value: 98
########################################################################################################################################################################################################
- Now Playing:
    - Jellyfin:
        icon: jellyfin.png
        href: http://jellyfin.volo.nas
        container: ix-jellyfin-jellyfin-1
        server: volo-docker
        description: Multimedia streaming library
        widget:
            type: jellyfin
            url: http://jellyfin.volo.nas
            key: {{HOMEPAGE_FILE_JELLYFIN_KEY}}
            enableBlocks: true 
            enableNowPlaying: true
            enableUser: true
            showEpisodeNumber: true 
            expandOneStreamToTwoRows: false
            fields: ["movies", "series"]
########################################################################################################################################################################################################
- Media Stack:
    - Stack:
        - Sonarr:
            icon: sonarr.png
            href: http://sonarr.volo.nas
            container: ix-sonarr-sonarr-1
            server: volo-docker
            description: Automate downloading series
            widget:
                type: sonarr
                url: http://sonarr.volo.nas
                key: {{HOMEPAGE_FILE_SONARR_KEY}}
                fields: ["wanted", "queued", "series"]
        - Radarr:
            icon: radarr.png
            href: http://radarr.volo.nas
            container: ix-radarr-radarr-1
            server: volo-docker
            description: Automate downloading movies
            widget:
                type: radarr
                url: http://radarr.volo.nas
                key: {{HOMEPAGE_FILE_RADARR_KEY}}
                fields: ["wanted", "queued", "movies"]
        - Bookshelf:
            icon: readarr.png
            href: http://bookshelf.volo.nas
            container: ix-bookshelf-bookshelf-1
            server: volo-docker
            description: Automate downloading books
            widget:
                type: readarr
                url: http://bookshelf.volo.nas
                key: {{HOMEPAGE_FILE_BOOKSHELF_KEY}}
                fields: ["wanted", "queued", "books"]
        - Bazarr:
            icon: bazarr.png
            href: http://bazarr.volo.nas
            container: ix-bazarr-bazarr-1
            server: volo-docker
            description: Media subtitles management
            widget:
                type: bazarr
                url: http://bazarr.volo.nas
                key: {{HOMEPAGE_FILE_BAZARR_KEY}}
                fields: ["missingEpisodes", "missingMovies"]
        - Prowlarr:
            icon: prowlarr.png
            href: http://prowlarr.volo.nas
            container: ix-prowlarr-prowlarr-1
            server: volo-docker
            description: Indexer manager for Usenet and torrents
            widget:
                type: prowlarr
                url: http://prowlarr.volo.nas
                key: {{HOMEPAGE_FILE_PROWLARR_KEY}}
                fields: ["numberOfGrabs", "numberOfQueries", "numberOfFailGrabs", "numberOfFailQueries"]
        - JellySeerr:
            icon: seerr.png
            href: http://seer.volo.nas
            container: ix-jelly-seerr-seerr-1
            server: volo-docker
            description: Request management for Jellyfin
            widget:
                type: seerr
                url: http://seer.volo.nas
                key: {{HOMEPAGE_FILE_SEER_KEY}}
                fields: ["pending", "approved", "available", "completed", "processing", "issues"]
    - Release Calendar:
        - " ":
            href: https://jellyfin.volo.nas
            widget:
                type: calendar
                firstDayInWeek: monday
                view: monthly
                maxEvents: 20
                showTime: true
                timezone: Australia/Melbourne
                integrations:
                    - type: sonarr
                      service_group: Stack
                      service_name: Sonarr
                      color: green
                      params:
                        unmonitored: false
                    - type: radarr
                      service_group: Stack
                      service_name: Radarr
                      color: blue
                      params:
                        unmonitored: false
########################################################################################################################################################################################################