---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

########################################################################################################################################################################################################
- Network System:
    - PiHole:
        icon: pi-hole.png
        href: http://pihole.volo.nas/admin
        container: ix-pihole-pihole-1
        server: local-docker
        description: Network-wide ad blocker
        widget:
            type: pihole
            url: http://pihole.volo.nas
            version: 6
########################################################################################################################################################################################################
- Network:
    - nGinx:
        icon: nginx.png
        href: http://nginx.volo.nas
        container: ix-nginx-proxy-manager-npm-1
        server: local-docker
        description: Web server and reverse proxy
        widget:
            type: npm
            url: http://nginx.volo.nas
            username: calza27@gmail.com
            password: {{HOMEPAGE_FILE_NGINX_KEY}}
    - unifi:
        icon: unifi.png
        href: https://192.168.3.21
        description: Network management controller
        widget:
            type: unifi
            url: https://192.168.3.21
            key: {{HOMEPAGE_FILE_UNIFI_KEY}}
########################################################################################################################################################################################################
- Media System:
    - truenas:
        icon: truenas.png
        href: http://volo.nas
        description: The OS
        widget:
            type: truenas
            url: http://volo.nas
            version: 2
            key: {{HOMEPAGE_FILE_TRUENAS_KEY}}
            enablePools: true 
            nasType: core
    - Speedtest:
        icon: speedtest-tracker.png
        href: http://speed.volo.nas
        server: local-docker
        container: ix-speedtest-tracker-speedtest-tracker-1
        description: Network speed tracker
        widget:
            type: speedtest
            url: http://speed.volo.nas
            bitratePrecision: 0
            fields: ["download", "upload", "ping"]
    - PiHole:
        icon: pi-hole.png
        href: http://pihole.volo.nas/admin
        container: ix-pihole-pihole-1
        server: local-docker
        description: Network-wide ad blocker
        widget:
            type: pihole
            url: http://pihole.volo.nas
            version: 6
    - nGinx:
        icon: nginx.png
        href: http://nginx.volo.nas
        container: ix-nginx-proxy-manager-npm-1
        server: local-docker
        description: Web server and reverse proxy
        widget:
            type: npm
            url: http://nginx.volo.nas
            username: calza27@gmail.com
            password: {{HOMEPAGE_FILE_NGINX_KEY}}
    - qBitTorrent:
        icon: qbittorrent.png
        href: http://qbit.volo.nas
        container: qbittorrent
        server: local-docker
        description: Torrent client
        widget:
            type: qbittorrent
            url: http://qbit.volo.nas
            username: admin
            password: {{HOMEPAGE_FILE_QBIT_KEY}}
            enableLeechProgress: true
            enableLeechSize: true
    - Media Uptime:
        icon: uptime-kuma.png
        href: http://kuma.volo.nas
        container: ix-uptime-kuma-uptime-kuma-1
        server: local-docker
        description: Monitor the status of your services
        widget:
            type: uptimekuma
            url: http://kuma.volo.nas
            slug: media-stack
    - Support Uptime:
        icon: uptime-kuma.png
        href: http://kuma.volo.nas
        container: ix-uptime-kuma-uptime-kuma-1
        server: local-docker
        description: Monitor the status of your services
        widget:
            type: uptimekuma
            url: http://kuma.volo.nas
            slug: support-svcs
########################################################################################################################################################################################################
- Now Playing:
    - Jellyfin:
        icon: jellyfin.png
        href: http://jellyfin.volo.nas
        container: ix-jellyfin-jellyfin-1
        server: local-docker
        description: Multimedia streaming library
        widget:
            type: jellyfin
            url: http://jellyfin.volo.nas
            key: {{HOMEPAGE_FILE_JELLYFIN_KEY}}
            enableBlocks: true 
            enableNowPlaying: true
            enableUser: true
            showEpisodeNumber: true 
            expandOneStreamToTwoRows: false
            fields: ["movies", "series"]
########################################################################################################################################################################################################
- Media Stack:
    - Stack:
        - Sonarr:
            icon: sonarr.png
            href: http://sonarr.volo.nas
            container: ix-sonarr-sonarr-1
            server: local-docker
            description: Automate downloading series
            widget:
                type: sonarr
                url: http://sonarr.volo.nas
                key: {{HOMEPAGE_FILE_SONARR_KEY}}
                fields: ["wanted", "queued", "series"]
        - Radarr:
            icon: radarr.png
            href: http://radarr.volo.nas
            container: ix-radarr-radarr-1
            server: local-docker
            description: Automate downloading movies
            widget:
                type: radarr
                url: http://radarr.volo.nas
                key: {{HOMEPAGE_FILE_RADARR_KEY}}
                fields: ["wanted", "queued", "movies"]
        - Bookshelf:
            icon: readarr.png
            href: http://bookshelf.volo.nas
            container: ix-bookshelf-bookshelf-1
            server: local-docker
            description: Automate downloading books
            widget:
                type: readarr
                url: http://bookshelf.volo.nas
                key: {{HOMEPAGE_FILE_BOOKSHELF_KEY}}
                fields: ["wanted", "queued", "books"]
        - Bazarr:
            icon: bazarr.png
            href: http://bazarr.volo.nas
            container: ix-bazarr-bazarr-1
            server: local-docker
            description: Media subtitles management
            widget:
                type: bazarr
                url: http://bazarr.volo.nas
                key: {{HOMEPAGE_FILE_BAZARR_KEY}}
                fields: ["missingEpisodes", "missingMovies"]
        - Prowlarr:
            icon: prowlarr.png
            href: http://prowlarr.volo.nas
            container: ix-prowlarr-prowlarr-1
            server: local-docker
            description: Indexer manager for Usenet and torrents
            widget:
                type: prowlarr
                url: http://prowlarr.volo.nas
                key: {{HOMEPAGE_FILE_PROWLARR_KEY}}
                fields: ["numberOfGrabs", "numberOfQueries", "numberOfFailGrabs", "numberOfFailQueries"]
        - JellySeerr:
            icon: seerr.png
            href: http://seer.volo.nas
            container: ix-jelly-seerr-seerr-1
            server: local-docker
            description: Request management for Jellyfin
            widget:
                type: seerr
                url: http://seer.volo.nas
                key: {{HOMEPAGE_FILE_SEER_KEY}}
                fields: ["pending", "approved", "available", "completed", "processing", "issues"]
    - Release Calendar:
        - " ":
            href: https://jellyfin.volo.nas
            widget:
                type: calendar
                firstDayInWeek: monday
                view: monthly
                maxEvents: 20
                showTime: true
                timezone: Australia/Melbourne
                integrations:
                    - type: sonarr
                      service_group: Stack
                      service_name: Sonarr
                      color: green
                      params:
                        unmonitored: false
                    - type: radarr
                      service_group: Stack
                      service_name: Radarr
                      color: blue
                      params:
                        unmonitored: false
########################################################################################################################################################################################################