---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/
title: pullyblank/Homepage
language: en
theme: dark
color: stone
target: _self
headerStyle: boxed
statusStyle: "dot"
hideVersion: false
disableCollapse: true

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

layout:
  # Emporer.net Items
  Network System:
    tab: Emporer.net
    style: row
    columns: 4
  Network:
    tab: Emporer.net
    style: row
    columns: 2
  # Volo.nas Items
  Media System:
    tab: Volo.nas
    style: row
    columns: 4
  Now Playing:
    tab: Volo.nas
    style: row
    columns: 1
  Media Stack:
    tab: Volo.nas
    style: row
    columns: 2
    Stack:
      style: row
      columns: 2
    Release Calendar:
      style: row
      columns: 1
