---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/
title: pullyblank/Homepage
language: en
theme: dark
color: stone
target: _self
headerStyle: boxed
statusStyle: "dot"
hideVersion: false
cardBlur: sm
background: 
  image: https://images.unsplash.com/photo-1637825891028-564f672aa42c
  blur: xl
  brightness: 90
  opacity: 60

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

layout:
  # Emporer.net Items
  Network System:
    tab: Emporer.net
    icon: mdi-desktop-classic-#FFFFFF
    style: row
    columns: 4
  Network:
    tab: Emporer.net
    icon: mdi-network-#FFFFFF
    style: row
    columns: 2
  # Volo.nas System Items
  System:
    style: row
    icon: mdi-desktop-classic-#FFFFFF
    columns: 4
    tab: Volo.nas System
  CPU Temps:
    icon: mdi-cpu-64-bit-#FFFFFF
    style: row
    columns: 4
    tab: Volo.nas System
  Disk Activity:
    icon: mdi-harddisk-#FFFFFF
    style: row
    columns: 1
    tab: Volo.nas System
    Disk Activity > Workload:
      icon: mdi-chart-timeline-variant-shimmer-#FFFFFF
      style: row
      columns: 4
    Disk Activity > Media:
      icon: mdi-video-#FFFFFF
      style: row
      columns: 4
    Disk Activity > Documents:
      icon: mdi-file-document-#FFFFFF
      style: row
      columns: 4
  System Apps:
    icon: mdi-application-#FFFFFF
    style: row
    columns: 4
    tab: Volo.nas System
  # Volo.nas App Items
  Now Showing:
    tab: Volo.nas Apps
    icon: mdi-video-account-#FFFFFF
    style: row
    columns: 2
  Media Stack:
    tab: Volo.nas Apps
    style: row
    icon: mdi-server-#FFFFFF
    columns: 4
