---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/
title: pullyblank/Homepage
language: en
theme: dark
color: stone
target: _self
headerStyle: boxed
statusStyle: "dot"
hideVersion: false
disableCollapse: true

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
